[package]
name = "atlas"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "atlas"
path = "src/main.rs"

[lib]
name = "atlas"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
prettytable-rs = "0.8.0"
regex = "1.5.4"
